---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"


inputs:
  - name: Bitbucket_Repository

outputs:
  - name: artifact-dir

run:
  path: source_code/ci/tasks/build-artifact.sh
