---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: source_code

run:
  path: source_code/ci/tasks/unit.sh
